---
title: "Gallery"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(algothemes)
library(gapminder)
library(janitor)
library(rnaturalearth)
library(scales)
library(sf)
library(tidyverse)
```

## Example dataset

```{r}
data_sf <- countries110 %>% 
  st_as_sf() %>% 
  as_tibble() %>% 
  select(iso_alpha = iso_a3, geometry)

data_clean <- gapminder %>% 
  mutate_if(~ is.factor(.), ~ as.character(.)) %>% 
  left_join(country_codes) %>% 
  left_join(data_sf) %>% 
  clean_names()

head(data_clean, 10)
```

## Scatter

### Example visualization

```{r}
data_viz <- data_clean %>% 
  filter(year == 2007)

ggplot(data_viz, aes(x = gdp_percap, y = life_exp)) +
  geom_point(alpha = 0.65) +
  geom_smooth(method = "loess") +
  scale_x_continuous(labels = dollar_format(scale = 1e-3, suffix = "K")) +
  labs(
    title = "How much for one year of life? It depends.",
    subtitle = "Life expectancy by GDP per capita for 142 countries in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = "GDP per Capita",
    y = "Life Expectancy"
  )
```

### With light theme

```{r}
ggplot(data_viz, aes(x = gdp_percap, y = life_exp)) +
  geom_point(colour = palette_algo_light("red"), alpha = 0.65) +
  geom_smooth(method = "loess", colour = palette_algo_light("purple"), fill = palette_algo_light("purple")) +
  scale_x_continuous(labels = dollar_format(scale = 1e-3, suffix = "K")) +
  labs(
    title = "How much for one year of life? It depends.",
    subtitle = "Life expectancy by GDP per capita for 142 countries in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = "GDP per Capita",
    y = "Life Expectancy"
  ) +
  theme_algo(mode = "light")
```

### With dark theme

```{r}
ggplot(data_viz, aes(x = gdp_percap, y = life_exp)) +
  geom_point(colour = palette_algo_dark("red"), alpha = 0.65) +
  geom_smooth(method = "loess", colour = palette_algo_dark("purple"), fill = palette_algo_dark("purple")) +
  scale_x_continuous(labels = dollar_format(scale = 1e-3, suffix = "K")) +
  labs(
    title = "How much for one year of life? It depends.",
    subtitle = "Life expectancy by GDP per capita for 142 countries in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = "GDP per Capita",
    y = "Life Expectancy"
  ) +
  theme_algo(mode = "dark")
```

## Bar

### Example visualization

```{r}
data_viz <- data_clean %>% 
  filter(year == 2007) %>% 
  arrange(desc(pop)) %>% 
  head(10) %>% 
  mutate(label = unit_format(scale = 1e-6, unit = "Million")(pop))

ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_col(aes(fill = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(fill = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  )
```

### With light theme

```{r}
ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_col(aes(fill = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(fill = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  ) +
  theme_algo(mode = "light") +
  scale_fill_algo(discrete = FALSE, mode = "light")
```

### With dark theme

```{r}
ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_col(aes(fill = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label), colour = "white") +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(fill = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  ) +
  theme_algo(mode = "dark") +
  scale_fill_algo(discrete = FALSE, mode = "dark")
```

## Lollipop

### Example visualization

```{r}
data_viz <- data_clean %>% 
  filter(year == 2007) %>% 
  arrange(desc(pop)) %>% 
  head(10) %>% 
  mutate(label = unit_format(scale = 1e-6, unit = "Million")(pop))

ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_segment(aes(xend = iso_alpha, y = 0, yend = pop, colour = pop)) +
  geom_point(aes(colour = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(colour = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  )
```

### With light theme

```{r}
ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_segment(aes(xend = iso_alpha, y = 0, yend = pop, colour = pop)) +
  geom_point(aes(colour = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(colour = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  ) +
  theme_algo(mode = "light") +
  scale_colour_algo(discrete = FALSE, mode = "light")
```

### With dark theme

```{r}
ggplot(data_viz, aes(x = reorder(iso_alpha, pop), y = pop)) +
  geom_segment(aes(xend = iso_alpha, y = 0, yend = pop, colour = pop)) +
  geom_point(aes(colour = pop)) +
  geom_text(aes(y = pop + max(pop) * 0.1, label = label), colour = "white") +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.15)), labels = unit_format(scale = 1e-6, unit = "M")) +
  coord_flip() +
  guides(colour = FALSE) +
  labs(
    title = "Getting crowded, isn't it?",
    subtitle = "Top 10 countries with most population in 2007",
    caption = "Source: Gapminder (http://gapminder.org)",
    x = NULL,
    y = NULL
  ) +
  theme_algo(mode = "dark") +
  scale_colour_algo(discrete = FALSE, mode = "dark")
```
